apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "4"
  creationTimestamp: "2025-06-05T19:10:33Z"
  generation: 5
  labels:
    app: quotes
    learn-kubernetes: quotes
    sandbox: learn-kubernetes
  name: quotes
  namespace: jo32218-dev
  resourceVersion: "1829676157"
  uid: 87eb6255-27e4-4064-87e9-a93eaa3b716e
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: quotes
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: quotes
    spec:
      containers:
      - env:
        - name: DB_SERVICE_NAME
          value: mysql
        image: ghcr.io/jo32218/quotes:v1
        imagePullPolicy: Always
        name: quotes
        ports:
        - containerPort: 10000
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 3
  conditions:
  - lastTransitionTime: "2025-06-05T19:32:57Z"
    lastUpdateTime: "2025-06-05T19:32:57Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-06-06T00:27:06Z"
    lastUpdateTime: "2025-06-06T00:27:06Z"
    message: ReplicaSet "quotes-7775f86588" has timed out progressing.
    reason: ProgressDeadlineExceeded
    status: "False"
    type: Progressing
  observedGeneration: 5
  readyReplicas: 3
  replicas: 4
  unavailableReplicas: 1
  updatedReplicas: 1
