apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
  creationTimestamp: "2025-06-05T19:29:55Z"
  generation: 4
  labels:
    app: quotesweb
    learn-kubernetes: quotesweb
    sandbox: learn-kubernetes
  name: quotesweb
  namespace: jo32218-dev
  resourceVersion: "1829671024"
  uid: 6177dc5b-4291-43a0-80b8-4d5c89c11ef5
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: quotesweb
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: quotesweb
    spec:
      containers:
      - image: ghcr.io/jo32218/quotesweb:v1
        imagePullPolicy: Always
        name: quotes
        ports:
        - containerPort: 3000
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 3
  conditions:
  - lastTransitionTime: "2025-06-05T22:52:52Z"
    lastUpdateTime: "2025-06-05T22:52:52Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-06-06T00:25:10Z"
    lastUpdateTime: "2025-06-06T00:25:10Z"
    message: ReplicaSet "quotesweb-76cc4b94b6" has timed out progressing.
    reason: ProgressDeadlineExceeded
    status: "False"
    type: Progressing
  observedGeneration: 4
  readyReplicas: 3
  replicas: 4
  unavailableReplicas: 1
  updatedReplicas: 1
